wandb_active: true
wandb_project_name: codon_transformer
checkpoint_dir: gptneo_128nodes_5epoch
num_nodes: 128
tokenizer_file: tokenizer_files/codon_wordlevel_100vocab.json
train_file: data/full_mdh_codon/train.txt
val_file: data/full_mdh_codon/val.txt
test_file: data/full_mdh_codon/test.txt
small_subset: false
enable_blast: false
blast_validation_file: data/full_mdh_codon/train_seqs.fasta
num_blast_seqs_per_gpu: 2
use_pretrained: false
batch_size: 8
epochs: 5
block_size: 512
val_check_interval: 100
accumulate_grad_batches: 4
generate_upon_completion: true
num_generated_seqs_per_gpu: 2