wandb_active: false
wandb_project_name: codon_transformer
checkpoint_dir: gptneo_128nodes_5epoch
load_from_checkpoint_dir: null #gptneo_128nodes_5epoch
node_local_path: /tmp
num_nodes: 1
tokenizer_file: ../../gene_transformer/tokenizer_files/codon_wordlevel_100vocab.json
train_file: data/full_mdh_fasta/train.fasta
val_file: data/full_mdh_fasta/val.fasta
test_file: data/full_mdh_fasta/test.fasta
enable_blast: true
blast_validation_file: data/full_mdh_fasta/train.fasta
blast_exe_path: ../../conda-env/bin/blastn
num_blast_seqs_per_gpu: 8
use_pretrained: false
batch_size: 8
epochs: 1
block_size: 512
accumulate_grad_batches: 4
generate_upon_completion: true
num_seqs_test: 8
