wandb_active: false
wandb_project_name: codon_transformer
checkpoint_dir: gptneo_128nodes_5epoch
load_from_checkpoint_dir: null #gptneo_128nodes_5epoch
num_nodes: 1
tokenizer_file: /global/cfs/cdirs/m3957/abrace/src/gene_transformer/gene_transformer/tokenizer_files/codon_wordlevel_100vocab.json
train_file: data/full_mdh_codon/train_seqs.fasta
val_file: data/full_mdh_codon/train_seqs.fasta
test_file: data/full_mdh_codon/train_seqs.fasta
enable_blast: false
blast_validation_file: data/full_mdh_codon/train_seqs.fasta
blast_exe_path: ../../conda-env/bin/blastn
num_blast_seqs_per_gpu: 2
use_pretrained: false
batch_size: 8
epochs: 2
block_size: 512
val_check_interval: 100
accumulate_grad_batches: 4
generate_upon_completion: true
num_generated_seqs_per_gpu: 2
